language: node_js
node_js:
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: michael.lee.allen@gmail.com
  api_key:
    secure: XO9fm9QAA5rdY8TP1CaFKH6ity4u0KiAy3i1NADBwLCIMzdAwKVdbxZqmlIYDCwvl2ZyOvLtuNGf2iIpmLz2+zFl4ygNRMafLqpjmQK7V9D4Cpo6gl/Z9GGI2583Tdv4AKEkKgkdEVP4m6Qah22CEkfzEo/B8hZpE3NhyJ9zuZ4=
  on:
    tags: true
